export const SIMPLE_FETCH = 'SIMPLE_FETCH'
export const SIMPLE_FETCH_SUCCESS = 'SIMPLE_FETCH_SUCCESS'
export const SIMPLE_FETCH_ERROR = 'SIMPLE_FETCH_ERROR'

export const LOGOUT = 'LOGOUT'

export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const SET_ON_DATASET = 'SET_ON_DATASET'
export const PUSH_TO_DATASET_LIST = 'PUSH_TO_DATASET_LIST'
export const UPDATE_TO_DATASET_LIST = 'UPDATE_TO_DATASET_LIST'
export const DELETE_DATASET_LIST = 'DELETE_DATASET_LIST'

export default {
    SIMPLE_FETCH,
    SIMPLE_FETCH_SUCCESS,
    SIMPLE_FETCH_ERROR,
    LOGOUT,
    LOGIN,
    LOGIN_SUCCESS,
    LOGIN_ERROR,
    SET_ON_DATASET,
    PUSH_TO_DATASET_LIST,
    UPDATE_TO_DATASET_LIST,
    DELETE_DATASET_LIST,

}
